# Setup Vagrant

    vagrant up

# SSh to the machine

    vagrant ssh


# Start keycloak

[source]
----
docker run -dti -e KEYCLOAK_USER=admin -e KEYCLOAK_PASSWORD=admin -p 172.28.128.4:8080:8080 -p 172.28.128.4:9990:9990 --name keycloak jboss/keycloak

docker run -dti -p 8080:8080 -p 9990:9990 --name keycloak-examples cmoulliard/keycloak-examples
docker run -dti -p 172.28.128.4:8080:8080 -p 172.28.128.4:9990:9990 --name keycloak-examples cmoulliard/keycloak-examples
docker run -dti -p 172.28.128.4:8080:8080 -p 172.28.128.4:9990:9990 -e KEYCLOAK_USER=admin -e KEYCLOAK_PASSWORD=admin999  --name keycloak-examples cmoulliard/keycloak-examples
----

# Access it from the browser of the host

[source]
----
http://172.28.128.4:8080/auth

or

http://centos-docker.vagrant.f8:8080/auth
----

# Compile Keycloak examples

[source]
----
wget http://downloads.jboss.org/keycloak/1.9.0.Final/keycloak-examples-1.9.0.Final.zip
unzip keycloak-examples-1.9.0.Final.zip
cd keycloak-examples-1.9.0.Final/saml
mvn clean install wildfly:deploy -Dwildfly.hostname=172.28.128.4  -Dwildfly.username=admin -Dwildfly.password=admin666
----

# Build our image

[source]
----
./docker build -t cmoulliard/keycloak-examples .
----

# Access the guest machine from the host

In order to access the guest machine from the machine, we must specify an ENV variable with the ip address or hostname of the docker daemon.

    export DOCKER_HOST=tcp://172.28.128.4:2375

The version of the docker daemon deployed is `1.9.1`. This is why we recommend that you install on your host the client 1.9.1.
Here are the instructions to follow to install it

[source]
----
wget https://get.docker.com/builds/Darwin/x86_64/docker-1.9.1
mv docker-1.9.1 docker
chmod +x docker
----

Next, move it to bin directory which is indluded within your PATH. Check if you can access the docker daemon and get information

    docker version


# Issue

There is a DNS issue with docker as we can't define as ENV variable the hostname of the VM created. This problem has been reported here :

* DNS issue --> https://groups.google.com/forum/#!msg/fabric8/sArNWH-p_7U/qCHOgzL4AwAJ

* Some utils cmds to run on the MacOS

[source]
----
cat /etc/resolver/vagrant.f8
scutil --dns
dns-sd -q centos7-docker.vagrant.f8
dig -p 10053 @localhost centos7-docker.vagrant.f8
----

# Useful commands

* Attach an existing process

    ./docker exec -i -t keycloak-examples bash

* Remove <none> images

    docker rmi -f $(docker images | grep "^<none>" | awk '{print $3}')







