# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

$vmMemory = ENV['FUSE_VM_MEMORY'] || 3000
$mavenVersion = ENV['MAVEN_VERSION'] || "3.2.3"
$gitRepoURL = ENV['GIT_REPO_URL'] || "https://github.com/FuseByExample/rest-dsl-in-action.git"
$gitRepoName = ENV['GIT_REPO_NAME'] || "rest-dsl-in-action"
$fuseVersion = ENV['FUSE_VERSION'] || "6.2.1.redhat-084"
$hostname = "fuse"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.hostname = $hostname

  config.vm.define "libvirt" do |cfg|
    cfg.vm.box = "fedora23-libvirt"
    # Configure private network between the guest and the host
    cfg.vm.network :private_network, 
        :ip => "172.28.128.4",
        :libvirt__network_name => "private"
  end

  config.vm.define "virtualbox" do |cfg|
    cfg.vm.box = "fedora23-virtualbox"
    cfg.vm.network "private_network", ip: "172.28.128.4"
  end

  # Use NFS for shared folders for better performance
  config.vm.synced_folder "tmp/", "/home/vagrant/tmp", nfs: true

  # set auto_update to false, if you do NOT want to check the correct 
  # additions version when booting this machine
  config.vbguest.auto_update = false

  # do NOT download the iso file from a webserver
  config.vbguest.no_remote = true

  config.vm.provider "virtualbox" do |v|
    v.memory = $vmMemory
    v.cpus = 2
    v.name = "dev-fuse-vm"
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  config.vm.provider :libvirt do |v, override|
    v.memory = $vmMemory
    v.driver = "kvm"
    v.cpus = 2
    v.volume_cache = "unsafe"
    v.machine_virtual_size = 45
    v.management_network_name = "default"
  end

  # Add bash profile
  # config.vm.provision "file", source: "env/bash_profile", destination: "/home/vagrant/.bash_profile"
  
  config.vm.provision "shell" do |s|
    s.path       = "bootstrap.sh"
    s.keep_color = true
    s.args       = [$vmMemory,$mavenVersion,$fuseVersion,$gitRepoURL,$gitRepoName]
  end

end
